model_config:
  unimodal_mobilenetv3_large:

    classifier:
      type: mlp
      params:
        in_dim: 960
        out_dim: 2
        hidden_dim: 768
        num_layers: 2

    image_encoder:
      name: mobilenetv3_large
      pool_type: avg
      num_output_features: 1
