model_config:
  late_fusion_efficientnet:

    image_classifier:
      type: mlp
      params:
        in_dim: 1280
        out_dim: 2
        hidden_dim: 768
        num_layers: 2

    text_classifier:
      type: mlp
      params:
        in_dim: 768
        out_dim: 2
        hidden_dim: 768
        num_layers: 2

    image_encoder:
      name: efficientnet-b0
      pool_type: avg
      num_output_features: 1

    text_encoder:
      type: transformer
      params:
        bert_model_name: bert-base-uncased
        hidden_size: 768
        num_hidden_layers: 12
        num_attention_heads: 12
        output_attentions: false
        output_hidden_states: false