model_config:
  unimodal_yolov5l:

    classifier:
      type: mlp
      params:
        in_dim: 25088
        out_dim: 2
        hidden_dim: 768
        num_layers: 2

    image_encoder:
      name: yolov5l
      pool_type: avg
      num_output_features: 1
